<?php

/***************************************************************
 * Extension Manager/Repository config file for ext: "plate_forms"
 *
 * Auto generated by Extension Builder 2018-07-18
 *
 * Manual updates:
 * Only the data in the array - anything else is removed by next write.
 * "version" and "dependencies" must not be touched!
 ***************************************************************/

$EM_CONF['plate_kesearch_ajaxbased'] = [
    'title' => 'Plate KeSearch Ajaxbased',
    'description' => 'a template stack that provides layouts for keSearch and Ajax based search results',
    'category' => 'plugin',
    'author' => 'Kolya von Droste zu Vischering',
    'author_email' => '',
    'state' => 'stable',
    'uploadfolder' => 0,
    'createDirs' => '',
    'clearCacheOnLoad' => 0,
    'version' => '1.0.0',
    'constraints' => [
        'depends' => [
            'typo3' => '11.0.0-11.5.99',
        ],
        'conflicts' => [],
        'suggests' => [],
    ],
];
